version: '3'

services:
  bb-8-demo:
    image: ddiu8081/bb-8-demo:latest
    container_name: bb-8-demo
    restart: always
    ports:
        - "3000:3000"
    environment:
      - OPENAI_API_KEY=YOUR_OPENAI_API_KEY
      # - HTTPS_PROXY=YOUR_HTTPS_PROXY
      # - OPENAI_API_BASE_URL=YOUR_OPENAI_API_BASE_URL
      # - HEAD_SCRIPTS=YOUR_HEAD_SCRIPTS
      # - PUBLIC_SECRET_KEY=YOUR_SECRET_KEY
      # - SITE_PASSWORD=YOUR_SITE_PASSWORD
      # - OPENAI_API_MODEL=YOUR_OPENAI_API_MODEL

